[build-system]
requires = ["setuptools>=75.0.0", "Cython>=3.0.0", "maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "loxmqttrelay"
version = "0.1.0"
description = "MQTT Relay for Loxone"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.0",
    "orjson>=3.8.0",
    "streamlit>=1.42.0",
    "pycryptodome>=3.18.0",
    "uvloop>=0.21.0",
    "gmqtt>=0.7.0",
    "construct>=2.10.70",
    "tomlkit>=0.13.0",
    "Cython>=3.0.0"
]

[project.optional-dependencies]
test = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.1",
    "pytest-cov>=4.1.0",
    "setuptools>=75.0.0"
]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.1",
    "pytest-cov>=4.1.0",
    "pyinstrument>=5.0.0",
    "setuptools>=75.0.0", 
    "maturin>=1.8",
    "setuptools-rust>=1.10.0"
]
build = [
    "setuptools>=75.0.0", 
    "maturin>=1.8",
    "Cython>=3.0.0",
    "setuptools-rust>=1.10.0"
]

[tool.uv]
native-tls = true

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["loxmqttrelay", "loxwebsocket"]

[project.scripts]
loxmqttrelay = "loxmqttrelay.main:main"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=. --cov-report=term-missing"
asyncio_mode = "strict"

[tool.maturin]
python-source = "src"
module-name = "loxmqttrelay._loxmqttrelay"
features = ["pyo3/extension-module"]
bindings = "pyo3"
