name: Rust Rewrite CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - rust-rewrite

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/loxmqttrelay

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: ${{ matrix.platform }}
          tags: |
            ${{ vars.DOCKER_USERNAME }}/loxmqttrelay:experimental-${{ github.sha }}
            ${{ vars.DOCKER_USERNAME }}/loxmqttrelay:experimental-latest
          build-args: |
            OPTIMIZATION_FLAGS=-O3 -march=native -ffast-math
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true